language: go
go:
  - 1.2
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
before_script:
  - rethinkdb --daemon
script:
  - go test -v ./...
after_script:
  - killall rethinkdb
