language: go
go:
  - 1.2
env:
  - ENV=test KIC_TEST_DB_HOST=localhost:28015 KIC_TEST_DB_NAME=kic_test
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/chuckpreslar/gofer
  - go get
before_script:
  - rethinkdb --daemon
script:
  - go test -v ./...
after_script:
  - killall rethinkdb
